language: ruby
rvm:
- 2.0.0
bundler_args: "--without production"
addons:
  postgresql: '9.3'
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate --trace
script:
- bundle exec rspec
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  app: sheltered-bastion-22670
  on:
    repo: carmelocuenca/shopaddict
  api_key:
    secure: Ykp74cdDnaEX+LQdF8DjwsxZNIZ0vVJGuhcC0XPTJf9ndGWpIFhczojzuHJJP6jBL/6qxzWkM21QCbSJkuHxhBqI9hpY+KFcUqmR1jPFBcE0X4o6FF07FbKRtL7n1+gBuShJDTNellbti0AKGSS3f6dN/M4kFStaG4mLoRfYwsJI1k5oyYI6XDScaIZVUSKHvLjHYJprwwtaFDiQK8t8b2O4Zie0YVVpLEZBYWyOPVxImBrH/sSxnGSWd0BsJLbCdMln+lHT9XGC6QHl4/HBwPeFZ2ib1zKKzaZc+Np3pm7ejMMsU2wp/Di2E6UtubjM0B09T8u1NZIQW4hFb0csP/CUzVZpO4vmUzOR0Xpi1+PdcxpgJYZ8uPeEdkG1WQIPst1nZVCFlXvC3IgwJHyD30vLcsPJiyIlpqhyGSfVbPIP6vuRvJYu+l7C3dDP5hsepIl9ZAWG6K1+2Ddoh0W7SI4k30SjfBRX9GJxhiwX0PmQAsc4C9wViN/6BF5XrCVgTPA5l7seBjfkRs8CeqvqLk5/bjRCUSfDa/1ecsefjrVJFreSFReRDUpivwKDLsZh+JjMYtIjyn5REEPQ5hPOUTkkq7/mRIrwhT9X2T0tT7cVDap1s6cByYcjARMRxf/K7w3nZe2acAPGg/z1lkypu4mXWLtvB7kZRW5tf0jiU0c=
env:
  global:
  - secure: XBCTzkqD+FcSK8RUDl10tKRA/oov1ISC0dMwq8GlGXS1uIeFVZXhhOPEGv1PgkjlCpo6PfKIK6m7KBUL6P+sm+O6qnto/L2Vln7JlLRm+XvZo1a6X3v0KbxUwXJACwHh2LWxXPpJPI3dkC0gZZ1J4PZrNcP+tK5qoh7vZNnFU5Ofb3/Q82vBOOUdyRetE3Twiw/UIntLArWies58T8ipF9qXQ0+7ctSlOXVQLV012/wtT6TOwS61hldsMPKaMmWII6/8e4wFMhxwbaNl7BayUqEZNGgMIbTbxa1AD0muHayHiDgekb5d3YWkC6Zvco1vnNGTxtCZ9efBxuvex+ufcs+yYZdAMjpm+oOc7ts80Dd4XEelYlUIzOk/oaGvBboqPZuZ+FN05aJ9WZKE6tDmb3xUTA6k8mvTNqGtWDqoRGHg95dmDHH26vnjgMbOuBCT3eLiJHB4PFvFf+X5t1rBssfWuCkbkVcuxsG6bcooEjsVxd7Yv2sMA3WiQUiBxn2F9mK7mu1khWJH5bLymUgMm/E3V0EuJ/UdSFr5R9u8/OUO5HAVQe/XkpNPPgXji8OBH/VIbvwr3OWtGaCfV4OQ0d0DyTtCZeDNqqzdLapt09jSV4RK0Q3vyP8+rJKSZIz+w3NsB9UBrI/qNtdmraKR09p0fGvu6trNgglQXGZ6HDY=
  - secure: B9E/3po3LGeI87By6YIpFq1eezvvdNGK6mH3hdtKy0kAbR1Hl0Rri9/iu072fphFBbFmN+eKYojmPYBoE7FU148Y8+99XKxZakDHi4oqc4l0ZRveUo8qsMR1i3tWcLC/jtUiR2tQPMtJu3JuLzWceL8xqZ6gtu2Xda3VkcQ721DWMtW/gHGBGT7C2ORMcYBe4bWKvV8nWNQK3idYnyy1hpk3/43jQWCT5a1tjbkoahkqTEVLSa093CoP7UmHKRHGzSRv1gXJ5Ik8p2sQF1HYpXcM9qBfyJMOHKU+IcBFVSS3+LLHN6+2lmTYNHpj8H1Fmw1NLn04FmzVpLF5DcvFZteWFuY6OZGfwXqQfHmRVP5JzWeAnNxx85Q97D4Cg/nvbuFRUVATpmLNpMDbeMg6EubcaBooTOAsIHEjI9kSZJNPPX+mRpEGVO9sTzoQYVbvQ3jTK0W5YnxbJ69/DnJBVVsKMK3J27Fs41kXqe+VSatehgVGHt+UTfH+gjx4xHOaSE4Wffc33sYDZSv+79Pt1F6W7Zd8e7Wjaj4KZyo9p1ACynSxyxs5oWH07anQwYWKK1idZKGY2GsQXXgmQgXEkiAcesyuI+GcLC1rn2tKRgP+v5IWjjc5nA4h7HK32nN12KybV5g+O0OZXLw96+As8MaAB2nuLOdNNjZYhVfCMso=
